### ISSUE TITLE
Does this tool support in-page html anchor?

### ISSUE THREAD

**Issue by lmaxeniro** [magiclen/markdown2html-converter#12]
Hi there,
Great and nice tool -- it works well on most of my markdown files.
However, I meet such an issue --if there are some in-page HTML anchor in my md file, after covert it does not work any more (anchor is removed) -- can that be avoided? check the help I didn't find the option like that...

example--this is my test md files:
```
# test page

[Introduction1](#section1)

[Introduction2](#section2)

---

<p id="section1">intr1</p>
<h2 id="section1">intr1_header2</h2>

<p id="section2">intr2</p>
<h2 id="section2">intr2_header2</h2>
```

after converting, all my HTML anchors of section1 and section2 will be removed..

**Comment by magiclen** [comment]
You can use the `--no-safe` option.

**Comment by lmaxeniro** [comment]
> You can use the `--no-safe` option.

Thanks a lot, this solved my problem.
