### ISSUE TITLE
Fix default architecture

### ISSUE THREAD

**Issue by zhum** [magiclen/markdown2html-converter#8]
I tried to compile this project under Ubuntu 20.04, but got a lot of errors. The cause was hardcoded arch. I changed all `x86_64-unknown-linux-musl` by `x86_64-unknown-linux-gnu` in Makefile and then compilation was OK. I suppose you need to document it or get the arch via `rustc -vV|grep 'host:' | sed 's/host: //'`, and then use it in your Makefile.

**Comment by magiclen** [comment]
I think you can just run `rustup target add x86_64-unknown-linux-musl` before you run `make`. Or you can just run `cargo build --release` with your default toolchain.

**Comment by magiclen** [comment]
I prefer to use musl libc to compile this crate because the binary executable file isn't dependent on any shared objects.

**Comment by zhum** [comment]
That's an option. Then, add please this command to the documentation.
